### ISSUE TITLE
bug: Normalization of names leads to lookup errors

### ISSUE THREAD

**Issue by mcab** [vsporeddy/name-a-woman#1]
https://github.com/vsporeddy/name-a-woman/blob/aecc5d5bdd638ff02db8f4450eafbd2d82bb725b/script.js#L63

Normalization of names can lead to issues, due to Wikipedia's API being case sensitive.

**Comment by vsporeddy** [comment]
What if it tries submitting the non-normalized name first, and then normalizes if that fails? Would that solve the issue @mcab

**Comment by mcab** [comment]
You could try fetching both in parallel, and then case:
- if one differs from the other, then choose the one with data
- if both return an actual response, check how similar they are
- if both fail to find the field, then reject

**Comment by vsporeddy** [comment]
Done. The Wikidata API conveniently has a normalize parameter. Also used the parallel fetch suggestion to handle name order reversal (I.e. Yoko Ono vs. Oko Yono).
