### ISSUE TITLE
bug: Non-closed span tags causing highlighting errors

### ISSUE THREAD

**Issue by mcab** [vsporeddy/name-a-woman#3]
https://github.com/vsporeddy/name-a-woman/blob/a897054a4559ed74dc678e33b748eecbf4b57026/index.html#L25-L26

should be:

```html
        <p><b>Women named</b>: <span id="womenNamed"></span></p>
        <p><b>Invalid guesses</b>: <span id="invalidGuesses"></span></p>
```

It fixes per-line selection:

![image](https://github.com/vsporeddy/name-a-woman/assets/4522043/67c9d983-5000-4390-991c-0e70423c4e0c)

**Comment by vsporeddy** [comment]
Fixed.
